workflows:
  build_apk:
    name: Build APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_COMPILE_SDK: "30"
        ANDROID_BUILD_TOOLS: "30.0.3"
        ANDROID_SDK_ROOT: /opt/android-sdk
    scripts:
      - name: Install Dependencies
        script: |
          cd android
          ./gradlew dependencies
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - cm.rajeev@gmail.com
